### ISSUE TITLE
Improve "time search" behaviour by returning the status during the time, not just changes

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#392]
**Is your feature request related to a problem? Please describe.**
Querying a time interval only returns status changes, and returns no data if no change occurred during that time frame

**Describe the solution you'd like**
When making a search with within a certain time interval i would like suzieq to think "where was the mac address during this time range" or "what was the status of bgp during this time range"

The expectation is that suzieq would return all known states within the time interval not just the changes.
So that if something didn't change, i would still get something back.

Take a mac address, if i search for that mac address between 10 AM and 11 AM , i want to know all the places where that mac address was regardless of the fact that it moved or not.

**Comment by ddutt** [comment]
This issue has been partially fixed with commit 3914ab91b0d524c956fcd39e88fed164b9db5ed4

Use view=latest to only see the latest value within a given time window. The default behavior has not changed. 

I say fixed partially because you still don't see the last value in the time window if nothing has changed in the specified time window. To see that you need to specify only the end-time. 

@anubisg1 and other users please comment on what you're expecting here.

**Comment by ddutt** [comment]
Fixed in 0.15.6
