### ISSUE TITLE
Poller Stalling

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#413]
**Describe the bug**
The poller seems to stall if there is a network issue of some sort.

**To Reproduce**
1. Spin up sq environment
2. create a form of network error so the poller cannot reach the devices. For example if you create an environment on laptop. Close/sleep laptop.
3. The poller then doesn't recover and marks devices as NEVERPOLL.

Full details here: [poller-issues.txt](https://github.com/netenglabs/suzieq/files/7091269/poller-issues.txt)

**Attach**
/tmp/sq-poller.log for poller errors. /tmp/sq-poller.log and /tmp/sq-coalescer.log for coalescer errors. TBD

 **Expected behavior**
Poller to recover and start polling device again upon network recovery.

**Additional context**

**Comment by felixblang** [comment]
This issue seems to still exist. When I first start the poller all devices show up as alive but after a few hours or days some devices are shown as NEVERPOLL. When i restart the poller everything is shown as alive again
[01.11.2021_suzieq-poller_log.txt](https://github.com/netenglabs/suzieq/files/7452254/01.11.2021_suzieq-poller_log.txt)
.

**Comment by ddutt** [comment]
Hi @felixblang What version of suzieq are you running?

**Comment by felixblang** [comment]
I'm using the suzieq:latest docker image, cli says version 0.14.2

**Comment by felixblang** [comment]
problem solved, i guess it helps to update my docker images... :(
